name: CI for dockerhub

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'app/**'
      - 'app3/**'
  workflow_dispatch:
    

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

env:
  image_prefix: docker.io/dleeha

jobs:
  build:
    name: build push DockerHub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-dir: ['app1', 'app2', 'app3']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: setup structure TEMP
      run: |
        cd app
        ln -s ../app3 .

    - name: ${{ matrix.build-dir }} - Set version info
      run: |
        cd app/${{ matrix.build-dir }}
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo "my_tag=${GITHUB_REF##*/}-${git_hash}" >> $GITHUB_ENV

        folder=$(pwd)
        echo "folder=${folder}"
        app_name="${folder##*/}"

        #echo "my_image=${{ env.image_prefix }}/${app_name}" >> $GITHUB_ENV

    - name: ${{ matrix.build-dir }} - Build and push to docker hub
      uses: docker/build-push-action@v2
      with:
        context: ./app/${{ matrix.build-dir }}
        push: true
        tags: ${{ env.image_prefix }}/${{ matrix.build-dir }}:${{ env.my_tag }}

    - name: ${{ matrix.build-dir }} - Update Version in manifest
      run: |
          version=$(cat ./app/${{ matrix.build-dir }}/charts/${{ matrix.build-dir }}/values.yaml | grep version: | awk '{print $2}')
          #sed -i "s|$version|${GITHUB_REF##*/}-${my_tag}|" ./${{ matrix.build-dir }}/charts/${{ matrix.build-dir }}/values.yaml
          sed -i "s|$version|${{ env.image_prefix }}/${{ matrix.build-dir }}:${my_tag}|" ./app/${{ matrix.build-dir }}/charts/${{ matrix.build-dir }}/values.yaml

    - name: ${{ matrix.build-dir }} - Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.build-dir }}-artifact
        path: ./app/${{ matrix.build-dir }}/charts/${{ matrix.build-dir }}/values.yaml
        if-no-files-found: error
        retention-days: 3

  update_manifest:
    needs: build
    name: updates manifest for k8s deployment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup structure TEMP
      run: |
        cd app
        ln -s ../app3 .

    - uses: actions/download-artifact@v3
      env: 
        app_name: app1
      with:
        name: ${{ env.app_name }}-artifact
        path: ./app/${{ env.app_name }}/charts/${{ env.app_name }}

    - uses: actions/download-artifact@v3
      env: 
        app_name: app2
      with:
        name: ${{ env.app_name }}-artifact
        path: ./app/${{ env.app_name }}/charts/${{ env.app_name }}

    - uses: actions/download-artifact@v3
      env: 
        app_name: app3
      with:
        name: ${{ env.app_name }}-artifact
        path: ./app/${{ env.app_name }}/charts/${{ env.app_name }}

    - name: teardown structure TEMP
      run: |
        cd app
        rm app3

    - name: Commit and push manifest changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Version updated

    
