# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ 'dev' ] # toggle activation

  # Allows you to run this workflow manually from the Actions tab
##  workflow_dispatch:

env:
  #REGISTRY: docker.io
  #IMAGE_NAME: ${{ github.repository }}
  image_prefix: docker.io/dleeha

jobs:
  # This workflow contains a single job called "build"
  build:
    ##dl:
    name: building and pushing to DockerHub
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: app1 - Set version info
      run: |
        cd ./app1
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo "my_tag=${GITHUB_REF##*/}-${git_hash}" >> $GITHUB_ENV

        folder=$(pwd)
        echo "folder=${folder}"
        app_name="${folder##*/}"

        echo "my_image=${{ env.image_prefix }}/${app_name}" >> $GITHUB_ENV


    - name: app1 - Build and push to docker hub
      uses: docker/build-push-action@v2
      with:
        context: ./app1
        push: true
        tags: ${{ env.my_image }}:${{ env.my_tag }}

    - name: app1 - Update Version in manifest
      run: |
          version=$(cat ./app1/charts/app1/values.yaml | grep version: | awk '{print $2}')
          #sed -i "s|$version|${GITHUB_REF##*/}-${my_tag}|" ./app1/charts/app1/values.yaml
          sed -i "s|$version|${my_image}:${my_tag}|" ./app1/charts/app1/values.yaml
          
    - name: app1 - Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Version updated

    


    - name: app2 - Set version info
      run: |
        cd ./app2
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo "my_tag=${GITHUB_REF##*/}-${git_hash}" >> $GITHUB_ENV

        folder=$(pwd)
        echo "folder=${folder}"
        app_name="${folder##*/}"

        echo "my_image=${{ env.image_prefix }}/${app_name}" >> $GITHUB_ENV

    - name: app2 - Build and push to docker hub
      uses: docker/build-push-action@v2
      with:
        context: ./app2
        push: true
        tags: ${{ env.my_image }}:${{ env.my_tag }}

    - name: app2 - Update Version in manifest
      run: |
          version=$(cat ./app2/charts/app2/values.yaml | grep version: | awk '{print $2}')
          #sed -i "s|$version|${GITHUB_REF##*/}-${my_tag}|" ./app2/charts/app2/values.yaml
          sed -i "s|$version|${my_image}:${my_tag}|" ./app2/charts/app2/values.yaml
          
    - name: app2 - Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Version updated